### ISSUE TITLE
Typo in the Markdown transcript: line 387

### ISSUE THREAD

**Issue by czuhajster** [susam/tucl#10]
Hey,

I have found a typo on [line 387](https://github.com/susam/tucl/blob/master/the-unix-command-language.md?plain=1#L387):

```
duplicated lines onto a `d` steam and all other lines (unique lines) onto
```

I think `steam` was meant to be `stream`.

Cheers,
Arkadiusz

**Comment by susam** [comment]
Thank you! Fixed in commit 7ec0cd1.
